hw3
katemalash/Rv-86.Python-Core pull request #12
Opened 2021-07-28 21:09 UTC by Crank09

2021-07-31 08:22 UTC, katemalash requested changes
Please fix calculations in tasks 3 and 5

2021-07-31 08:22 UTC, katemalash commented on Okhmak/HW3/task1_hw3.py
> +v2 = int(input("V2? "))
What do v1 and v2 mean? It would be great to name variables more informative

2021-07-31 08:22 UTC, katemalash commented on Okhmak/HW3/task2_hw3.py
> +print(byte,"is",byte/2048,"bytes in megabytes")
Are you sure this is correct formula?

2021-07-31 08:22 UTC, katemalash commented on Okhmak/HW3/task3_hw3.py
> +print("Perimeter of our rectangle is",P_rect,"cm.")
Good decision

2021-07-31 08:22 UTC, katemalash commented on Okhmak/HW3/task4_hw3.py
> +P_circle = 2*(pi*r_circle)
Are these braces mandatory here?

2021-07-31 08:22 UTC, katemalash commented on Okhmak/HW3/task5_hw3.py
> +hypotenuse = 0.5*(legA**2+legB**2)
Are you sure this is correct formula?

2021-07-31 11:58 UTC, Crank09 commented on Okhmak/HW3/task1_hw3.py
> +v2 = int(input("V2? "))
> What do v1 and v2 mean? It would be great to name variables more informative

v1,v2 means "variables 1,2". I think this is enough for a training code

2021-07-31 12:39 UTC, Crank09 commented on Okhmak/HW3/task4_hw3.py
> +P_circle = 2*(pi*r_circle)
Не обов'язкові. Я думав, так легше читається код.

2021-08-02 13:05 UTC, katemalash approved these changes
It Works now. Please merge this pull-request

2021-08-02 13:05 UTC, katemalash commented on Okhmak/HW3/task1_hw3.py
> +v2 = int(input("V2? "))
It would be better to give the variables more meaningful names.

2021-08-02 13:05 UTC, katemalash commented on Okhmak/HW3/task2_hw3.py
> +print(byte,"is",byte/1048576,"bytes in megabytes")
Good Now.

2021-08-02 13:05 UTC, katemalash commented on Okhmak/HW3/task5_hw3.py
> +hypotenuse = (legA**2+legB**2)**0.5
Good Now

2021-08-02 13:12 UTC, Crank09 commented on Okhmak/HW3/task1_hw3.py
> +v2 = int(input("V2? "))
Okay, I'll keep it in mind.

2021-08-02 13:12 UTC, merged