Terefenko HW3
katemalash/Rv-86.Python-Core pull request #20
Opened 2021-07-30 10:22 UTC by olhaterefenko

task1
task2
task3
task4
task5
task6 and tests for it

2021-08-02 13:34 UTC, katemalash requested changes
Please change the destination branch to your main branch

2021-08-02 16:22 UTC, olhaterefenko commented
> Please change the destination branch to your main branch

done

2021-08-04 11:41 UTC, katemalash approved these changes
Good Job. Please merge this pull request

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Mark_collection.py
> +        self.unique_marks_collection.update({collection_name: unique_marks})
Good Way

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/test_mark_colection.py
> +            assert list(self.my_collection.unique_marks_collection[collection_name]).count(mark) == 1
Oh, even with classes) Nice :-)

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Task_5.py
> +print("hypotenuse_triangle:", hypotenuse_triangle)
Good Way

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Task_4.py
> +area_circle = 3.14 * radius ** 2
It would be better to create variable pi and use it or `import math `and use `math.pi`

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Task_4.py
> +print("perimeter_circle:", perimeter_circle)
good way

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Task_3.py
> +print("perimeter_rectangle:", perimeter_rectangle)
Good Decision

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Task_2.py
> +print(bytes / 1024, "kilobytes\n" + str(bytes / 1024 / 1024), "megabytes")
Good Decision

2021-08-04 11:41 UTC, katemalash commented on terefenko/HW3/Task_1.py
> +print("number b:", b)
Nice

2021-08-04 11:58 UTC, merged