Anastasiia pedorenko hw 4
katemalash/Rv-86.Python-Core pull request #25
Opened 2021-08-01 14:23 UTC by ananas111

2021-08-02 13:52 UTC, katemalash requested changes
Please fix the calculations for the triangle's square

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task1.py
> +print(f"year belongs to {century} century")
Good Decision

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task2.py
> +geometric_shapes = str(
is it mandatory here to cast to `str()`?

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task2.py
> +if geometric_shapes == 'rectangle' or geometric_shapes == 'triangle':
The formula for triangle square is not the same as the formula for rectangle square (Heron's formula). Please fix these calculations

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task3.py
> +print(f"{status}{number_of_digits}-digits")
Good Decision

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task4.py
> +if square_stage < square_hall and ((square_hall ** 0.5 / 2) - radius) >= K:
Is the first condition mandatory here?

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task5.py
> +    f"we can exchange money into {banknote200} banknotes by 200 UAH, {banknote100} banknotes by 100 UAH, {banknote10} banknotes by 10 UAH, {banknote1} banknotes by 1 UAH ")
Good Decision

2021-08-02 13:52 UTC, katemalash commented on Pedorenko/HW4/task6.py
> +    print('you entered the wrong number')
Good Solution

2021-08-02 19:42 UTC, ananas111 commented on Pedorenko/HW4/task2.py
> +if geometric_shapes == 'rectangle' or geometric_shapes == 'triangle':
I fixed it, thanks!

2021-08-02 19:43 UTC, ananas111 commented on Pedorenko/HW4/task2.py
> +geometric_shapes = str(
nope

2021-08-02 19:43 UTC, ananas111 commented on Pedorenko/HW4/task4.py
> +if square_stage < square_hall and ((square_hall ** 0.5 / 2) - radius) >= K:
nope

2021-08-02 20:14 UTC, ananas111 commented
I edited the homework and committed the result.

2021-08-03 09:55 UTC, katemalash approved these changes
Good Job. Please merge this pull request

2021-08-03 11:39 UTC, merged