Home work 4
katemalash/Rv-86.Python-Core pull request #28
Opened 2021-08-02 16:57 UTC by olhaterefenko

2021-08-03 14:51 UTC, katemalash requested changes
Please fix calculations for circle square

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_1.py
> +elif years % 400 == 0:
Is it possible to place all true conditions in one branch?

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_2.py
> +    perimeter = (side_a + side_b + side_c)/2
Is it correct to name this variable perimeter?

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_2.py
> +    square_circle = 2 * 3.14 * radius_circle
Are you sure this is correct formula?

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_3.py
> +    print("the number is another")
Is it possible to count the length of input value?

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_4.py
> +    print("Something went wrong!")
It works

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_5.py
> +regex_pattern = '^[0-9]+$'
Maybe .isdigit() is more effective way?)

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_5.py
> +    print("You input incorrect value. Only digit is allowed.")
Good decision

2021-08-03 14:51 UTC, katemalash commented on terefenko/HW4/Task_4_6.py
> +    print("The place number is incorrect!")
Nice!

2021-08-03 15:06 UTC, olhaterefenko commented on terefenko/HW4/Task_4_3.py
> +    print("the number is another")
Yes, I'll correct it.

2021-08-03 15:22 UTC, olhaterefenko commented on terefenko/HW4/Task_4_5.py
> +regex_pattern = '^[0-9]+$'
Maybe)

2021-08-03 19:03 UTC, olhaterefenko commented on terefenko/HW4/Task_4_1.py
> +elif years % 400 == 0:
done

2021-08-03 19:04 UTC, olhaterefenko commented on terefenko/HW4/Task_4_2.py
> +    perimeter = (side_a + side_b + side_c)/2
fixed

2021-08-03 19:04 UTC, olhaterefenko commented on terefenko/HW4/Task_4_2.py
> +    square_circle = 2 * 3.14 * radius_circle
fixed

2021-08-03 19:04 UTC, olhaterefenko commented on terefenko/HW4/Task_4_3.py
> +    print("the number is another")
done

2021-08-04 11:44 UTC, katemalash approved these changes
Well Now!
Please merge this pull request

2021-08-04 11:59 UTC, merged