Nazar fomenko hw4
katemalash/Rv-86.Python-Core pull request #31
Opened 2021-08-04 04:00 UTC by NazarF-o

2021-08-10 09:58 UTC, katemalash requested changes
Please fix the mentioned inaccuracies

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-1.py
> +if year % 4 == 0 and year % 100 != 0 or year % 1000 == 0:
What about 1900?

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-2.py
> +    print('Hypotenuse of a right triangle (AB) = %.2f' % h)
It was required to calculate the Square and Perimeter, not hypotenuse

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-6.py
> +np = int(input('Enter number of a place :'))
It would be better to name this variable place_number

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-6.py
> +    print('Reserved number - compartment')
Are you sure this schema is correct?

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-5.py
> +    banknote_1 = (money - (banknote * 200)) // 100
What will be printed if we have 800 UAH?

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-3.py
> +    print('Zero number')
This decision works but it would be better to use` len`

2021-08-10 09:58 UTC, katemalash commented on Fomenko/HW4/HW4-4.py
> +    S_rectangle = (4 * r_circle ** 2)
Why do you use this formula?

2021-08-10 12:37 UTC, NazarF-o commented on Fomenko/HW4/HW4-1.py
> +if year % 4 == 0 and year % 100 != 0 or year % 1000 == 0:
1900 This year is  not intercalary, 20 century
https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9_%D0%B3%D0%BE%D0%B4

2021-08-10 12:38 UTC, NazarF-o commented on Fomenko/HW4/HW4-2.py
> +    print('Hypotenuse of a right triangle (AB) = %.2f' % h)
I will correct

2021-08-10 12:39 UTC, NazarF-o commented on Fomenko/HW4/HW4-6.py
> +np = int(input('Enter number of a place :'))
Thanks for the clarification

2021-08-10 12:43 UTC, NazarF-o commented on Fomenko/HW4/HW4-5.py
> +    banknote_1 = (money - (banknote * 200)) // 100
800 to 200 will be 4 bills. The smallest number

2021-08-10 12:46 UTC, NazarF-o commented on Fomenko/HW4/HW4-6.py
> +    print('Reserved number - compartment')
Я робив по такій логіці. В вагоні може бути багато номерів, яка роскладка по порядку я не знаю (припустимо). 4 місця це купе, а ще 2 це бокові. Виправлю

2021-08-10 12:48 UTC, NazarF-o commented on Fomenko/HW4/HW4-3.py
> +    print('Zero number')
Thanks for the clarification

2021-08-10 12:49 UTC, NazarF-o commented on Fomenko/HW4/HW4-3.py
> +    print('Zero number')
I will correct

2021-08-10 12:59 UTC, NazarF-o commented on Fomenko/HW4/HW4-4.py
> +    S_rectangle = (4 * r_circle ** 2)
На мій погляд ця формула найбільше підходить для вирішення поставленої задачі. Та має практичне застосування.

2021-08-11 05:52 UTC, NazarF-o commented
Done

2021-08-17 08:44 UTC, katemalash approved these changes
Looks good now. Please merge this pull-request

2021-08-18 04:14 UTC, merged